### ISSUE TITLE
Why there is mixed syntax module.exports vs export in different files ?

### ISSUE THREAD

**Issue by prisonier** [stylesuxx/generator-react-webpack-redux#14]
Hi,

I'm very unfamiliar with ES6 syntax and I would like to have the oppurtunity to clarify some stuff.

When I generate an action with the generator, I get this code : 

``` javascript
// containers/App.js

function mapDispatchToProps(dispatch) {
  /* Populated by react-webpack-redux:action */
  const actions = { test: require('../actions/test.js') };
  const actionMap = { actions: bindActionCreators(actions, dispatch) };
  return actionMap;
}
```

``` javascript
// actions/test.js

module.exports = function(parameter) {
  return { type: 'TEST', parameter };
};
```

Is there any technical reason to do this instead of export/import explicitely or is it just to have a shorter code ? 
In the containers/App.js there is some imports, why did you decide to mix export/import and module.exports/require() ?

**Comment by prisonier** [comment]
I think I start to understand, if I use ES6 export, I can have multiple actions by file but I still have to explicitely map actions in the actions object in App.js + I must import the module at the begining of the file.
With the module.exports/require() you don't have an additionnal import line but you can only have one action per file which is maybe more consistent.

Nice generator !

**Comment by stylesuxx** [comment]
Hey,
I think you basically answered your own question.

The point is, you could do it either way, but since I am adding code to existing files via AST, I want to make sure to not break anything when adding new actions via generator and this was the best way I could think about.

One file per action, one export per action. So when mapping adding code via AST I only need to add one entry to the actions object without touching anything else.

Hope this helps.

**Comment by prisonier** [comment]
Hi, this helps I now understand. Thanks
