### ISSUE TITLE
Best way to declare action name as constants ?

### ISSUE THREAD

**Issue by prisonier** [stylesuxx/generator-react-webpack-redux#16]
Hi,

I would like to declare action name as constant mainly to avoid typo when using them. 

For now the best way I can find without breaking anything in the genrator is to create a const.js file into the action folder and then import them where I need them.

```javascript
//actions/todo/const.js

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
```

```javascript
//actions/todo/setVisibilityFilter.js - generated by the generator

import { SET_VISIBILITY_FILTER } from './const'

module.exports = function(filter) {
  return { type: SET_VISIBILITY_FILTER, filter };
};
```

```javascript
// reducers/todo/visibilityFilter.js - generated by the generator

import { SET_VISIBILITY_FILTER } from '../../actions/todo/const'

const initialState = 'SHOW_ALL'

module.exports = function(state = initialState, action) {

  switch(action.type) {

    case SET_VISIBILITY_FILTER: {
      return action.filter;
    }

    default: {
      return state;
    }
  }
}
```

I guess that it would be very easily implemented by the generator as there is only one file to add and edit when actions are generated so if it is not yet possible to do this with it, it could be an enhencement.

**Comment by stylesuxx** [comment]
This, in fact, is on my Todo list, just wanted to wait until someone complains about it.
If you'd like you could commit a PR with this functionality - what do you think?

**Comment by prisonier** [comment]
I tried to do something but I don't succeded in creating 2 actions with tests so I cannot test when const.js already exists. But I guess it is working.

I changed the createGeneratedAction function in action/indexTest.js because I tried to create an array of actions but I miserably failed. 

[Could you have a look at my repo please ?](https://github.com/prisonier/generator-react-webpack-redux)

**Comment by stylesuxx** [comment]
OK, I took a glance over it, seems you are reading this file and writing directly to it.
I used esprima for AST traversal in order to add content to existing files. You can see how I attach for examples the actions to the app [here](https://github.com/prisonier/generator-react-webpack-redux/blob/master/generators/action/index.js#L12).

I would suggest to add the base template for the const file in the root generator. Only needs to be an empty file with a comment that it is filled by the generator.

Then when the action is created simply append the const like in the link above via AST traversal.

**Comment by prisonier** [comment]
Ok I first didn't understand why you was talking about the root folder but I finally get it working with and without namespaces.

I already read the code to attach actions to the app but I didn't really understand it so I used "ejs" package, feel free to refactor but it is working like this.

I tried to be the cleanest possible and every code should be commented.

**Comment by prisonier** [comment]
https://github.com/stylesuxx/generator-react-webpack-redux/pull/18

**Comment by stylesuxx** [comment]
Thanks, but you are still not using AST traversal to attach the const ;-)
You will not need to use ejs then.

I will pull your branch and make the adaptions I am talking about - maybe I just did not make my point clear enough...

If you do not understand my code, please feel free to ask - we are here to learn, and I am happy explaining stuff, also because it lets my think about what I did, especially when someone has problems understanding my code. I can learn from this too, so do not be shy.

**Comment by prisonier** [comment]
Yes I was bloking on this point ;-)

I'm not shy, I just didn't want spend more time for this and this is why I choose to do it with tools I know.

I didn't understand you absolutely wanted using AST but I can understand you want the code to be consistent and use the same tools.

**Comment by stylesuxx** [comment]
Merged your PR to develop branch, made my adaptions.
This will be in the next release.

Thank you for your contribution.

**Comment by prisonier** [comment]
Nice :) 
The code is cleaner that way
