### ISSUE TITLE
Multiple actions in one action file

### ISSUE THREAD

**Issue by kamilglod** [stylesuxx/generator-react-webpack-redux#7]
I'm new in redux and react and I'm not sure how to implement multiple actions in one action file, 
because of your `mapDispatchToProps` I'm forced to keep one action per file, or maybe there is an other option to handle it? 

If we will look at the containers/App.js file we can see this line of code:
`const actionMap = { actions: bindActionCreators(actions, dispatch) };`
and yomen generates imports like that:
`const actions = { items: require('../actions/items.js') };`
so return values of actions have to be a single function by default

**Comment by stylesuxx** [comment]
To be honest, this is by design. Every action in a single file. This way you can look in the actions directory and quickly see all actions the app is composed of, in one place.

What would your argument be to have multiple actions in the same file? Maybe I am just overlooking something ;-)

**Comment by kamilglod** [comment]
With that approach (keeping multiple actions in one file) we could organize actions belonging to same sort (like managing user data)
But as I said I'm a newbie so maybe I don't understand something

**Comment by stylesuxx** [comment]
Then namespace your actions, then you have dir structure like so:
```
actions
  user
    add.js
    delete.js
    edit.js
```

**Comment by kamilglod** [comment]
with this approach we will end up with dozen of files in each dir with couple lines of code :/

**Comment by stylesuxx** [comment]
So, what? Sorry, but I do not see the problem with that. I prefer having as little code per file as possible. And having the files named properly. This way I know exactly where to look if I want to make any changes. I do not have to search a file with (potentially) hundreds of lines of code just to make my changes.

Also I try to write reusable code, so this way I can just copy a single file of which I know I can use, instead of sifting through hundreds of lines of code to copy/paste that one function I need.

Or are you concerned about delivering all those files? This is not a problem, since babel will transpile all the code into a single file anyway,...

So your suggestion would be to group actions by their domain in a single file? If you want you can commit a PR enabling this functionality during project setup and I will happily merge it.
